//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All our cars undergo a rigorous 150-point inspection before sale. We guarantee the technical condition and legal purity of every vehicle..
        /// </summary>
        public static string All_our_cars_undergo_a_rigorous_150_point_inspection_before_sale__We_guarantee_the_technical_condition_and_legal_purity_of_every_vehicle_ {
            get {
                return ResourceManager.GetString("All our cars undergo a rigorous 150-point inspection before sale. We guarantee th" +
                        "e technical condition and legal purity of every vehicle.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Prices.
        /// </summary>
        public static string Best_Prices {
            get {
                return ResourceManager.GetString("Best Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Catalog.
        /// </summary>
        public static string Browse_Catalog {
            get {
                return ResourceManager.GetString("Browse Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars in Stock.
        /// </summary>
        public static string Cars_in_Stock {
            get {
                return ResourceManager.GetString("Cars in Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified Quality.
        /// </summary>
        public static string Certified_Quality {
            get {
                return ResourceManager.GetString("Certified Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Support.
        /// </summary>
        public static string Fast_Support {
            get {
                return ResourceManager.GetString("Fast Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Your Dream Car.
        /// </summary>
        public static string Find_Your_Dream_Car {
            get {
                return ResourceManager.GetString("Find Your Dream Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Clients.
        /// </summary>
        public static string Happy_Clients {
            get {
                return ResourceManager.GetString("Happy Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Home_Page {
            get {
                return ResourceManager.GetString("Home Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than just a dealership.
        /// </summary>
        public static string More_than_just_a_dealership {
            get {
                return ResourceManager.GetString("More than just a dealership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team is ready to help you 24/7 with any questions regarding purchase, registration, or maintenance..
        /// </summary>
        public static string Our_team_is_ready_to_help_you_24_7_with_any_questions_regarding_purchase__registration__or_maintenance_ {
            get {
                return ResourceManager.GetString("Our team is ready to help you 24/7 with any questions regarding purchase, registr" +
                        "ation, or maintenance.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium quality, verified history, and best prices in the region..
        /// </summary>
        public static string Premium_quality__verified_history__and_best_prices_in_the_region_ {
            get {
                return ResourceManager.GetString("Premium quality, verified history, and best prices in the region.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Available Cars.
        /// </summary>
        public static string See_Available_Cars {
            get {
                return ResourceManager.GetString("See Available Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t just sell cars; we provide a lifestyle. Since 2010, we have helped over 5000 clients find their perfect vehicle. Our mission is to make the car buying process transparent, simple, and enjoyable..
        /// </summary>
        public static string We_don_t_just_sell_cars__we_provide_a_lifestyle__Since_2010__we_have_helped_over_5000_clients_find_their_perfect_vehicle__Our_mission_is_to_make_the_car_buying_process_transparent__simple__and_enjoyable_ {
            get {
                return ResourceManager.GetString("We don\'t just sell cars; we provide a lifestyle. Since 2010, we have helped over " +
                        "5000 clients find their perfect vehicle. Our mission is to make the car buying p" +
                        "rocess transparent, simple, and enjoyable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We monitor the market daily to offer you the most competitive prices. Flexible financing and trade-in options available..
        /// </summary>
        public static string We_monitor_the_market_daily_to_offer_you_the_most_competitive_prices__Flexible_financing_and_trade_in_options_available_ {
            get {
                return ResourceManager.GetString("We monitor the market daily to offer you the most competitive prices. Flexible fi" +
                        "nancing and trade-in options available.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of Experience.
        /// </summary>
        public static string Years_of_Experience {
            get {
                return ResourceManager.GetString("Years of Experience", resourceCulture);
            }
        }
    }
}
